default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>

development:
  <<: *default
  database: s_original

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  sslmode: <%= ENV.fetch("DB_SSLMODE", "require") %>
